# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Christian Aldridge @ StudioZut
email: studiozut@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Posts about web development and professional information for Christian Aldridge
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://studiozut.github.io" # the base hostname & protocol for your site
twitter_username: studiozut
github_username:  studiozut
linkedin_username: studiozut
homepage_intro: > # this means to ignore newlines until "markdown:"
  Christian is a web developer for the Scholarly Technology Group at the George Washington University. He’s a ‘full stack’ developer with a focus on lean UX, responsive design and usability. Christian presents regularly within George Washington University, showcases his team’s work at lightning talks and regional conferences and runs technology workshops for his job as well as events like the Uncommon Alliance STEM Conference in DC. He has a background in teaching and theatre in addition to 10 years in web development. He’s a Drupal member and member of the User Experience Professionals Association (UXPA-DC). Posts about web development from a full stack developer
# Build settings
markdown: kramdown
theme: minima
